# -------------------------
# Build Stage
# -------------------------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY FoodOrderingApplicationFigma.csproj ./
RUN dotnet restore FoodOrderingApplicationFigma.csproj

COPY . .
RUN dotnet publish FoodOrderingApplicationFigma.csproj -c Release -o /app/publish

# -------------------------
# Runtime Stage
# -------------------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "FoodOrderingApplicationFigma.dll"]
