// <auto-generated />
using System;
using FoodOrderingApplicationFigma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderingApplicationFigma.Migrations
{
    [DbContext(typeof(FoodOrderingDbContext))]
    [Migration("20251117174918_FoodDelivery")]
    partial class FoodDelivery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AddressId")
                        .HasName("PK__Addresse__091C2AFBF205A080");

                    b.HasIndex("CityId");

                    b.HasIndex("StateId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId")
                        .HasName("PK__Admins__719FE4886B1779A7");

                    b.HasIndex(new[] { "UserId" }, "UQ__Admins__1788CC4D4D08B65B")
                        .IsUnique();

                    b.ToTable("Admins", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId")
                        .HasName("PK__Carts__51BCD7B75BF44B1B");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__488B0B0A60722FBE");

                    b.HasIndex("CartId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("CartItems", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21B767040D9CA");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64D8FC64ECDA");

                    b.HasIndex(new[] { "UserId" }, "UQ__Customer__1788CC4DA3641E4D")
                        .IsUnique();

                    b.ToTable("Customers", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.MenuCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId")
                        .HasName("PK__MenuCate__19093A0B49DC95DC");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuCategories", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MenuItemId")
                        .HasName("PK__MenuItem__8943F7229240A974");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.OTPVerification", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OtpID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EmailAddress");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiryTime");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsUsed");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MobileNumber");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("OTPCode");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Purpose");

                    b.HasKey("OtpId")
                        .HasName("PK__OTPVerification__OtpId");

                    b.HasIndex("CustomerId");

                    b.ToTable("OTPVerifications", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BCFFEBAB133");

                    b.HasIndex("AddressId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId")
                        .HasName("PK__OrderIte__57ED0681851F4B42");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RestaurantId")
                        .HasName("PK__Restaura__87454C95DE87DA2E");

                    b.HasIndex("CityId");

                    b.HasIndex("StateId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Restaura__1788CC4D4F1200E2")
                        .IsUnique();

                    b.ToTable("Restaurants", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CEE15BC039");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Reviews", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A645B282C");

                    b.ToTable("Roles", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StateId")
                        .HasName("PK__States__C3BA3B3A6F7E7A4F");

                    b.HasIndex(new[] { "StateName" }, "UQ__States__554763154C99B2EC")
                        .IsUnique();

                    b.ToTable("States", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C5B57DA4F");

                    b.HasIndex("Role");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users", "FoodOrderingSystem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Address", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Addresses__CityI__5629CD9C");

                    b.HasOne("FoodOrderingApplicationFigma.Models.State", "State")
                        .WithMany("Addresses")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__Addresses__State__571DF1D5");

                    b.HasOne("FoodOrderingApplicationFigma.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Addresses__UserI__5535A963");

                    b.Navigation("City");

                    b.Navigation("State");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Admin", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("FoodOrderingApplicationFigma.Models.Admin", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Admins__UserId__3E52440B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Cart", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Carts__UserId__619B8048");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.CartItem", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItems__CartI__656C112C");

                    b.HasOne("FoodOrderingApplicationFigma.Models.MenuItem", "MenuItem")
                        .WithMany("CartItems")
                        .HasForeignKey("MenuItemId")
                        .IsRequired()
                        .HasConstraintName("FK__CartItems__MenuI__66603565");

                    b.Navigation("Cart");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.City", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__StateId__49C3F6B7");

                    b.Navigation("State");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Customer", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("FoodOrderingApplicationFigma.Models.Customer", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Customers__UserI__4222D4EF");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.MenuCategory", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.Restaurant", "Restaurant")
                        .WithMany("MenuCategories")
                        .HasForeignKey("RestaurantId")
                        .IsRequired()
                        .HasConstraintName("FK__MenuCateg__Resta__59FA5E80");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.MenuItem", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.MenuCategory", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__MenuItems__Categ__5DCAEF64");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.OTPVerification", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK__OTPVerification__Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Order", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__AddressI__6D0D32F4");

                    b.HasOne("FoodOrderingApplicationFigma.Models.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__Restaura__6C190EBB");

                    b.HasOne("FoodOrderingApplicationFigma.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__UserId__6B24EA82");

                    b.Navigation("Address");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.OrderItem", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__MenuI__71D1E811");

                    b.HasOne("FoodOrderingApplicationFigma.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__70DDC3D8");

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Restaurant", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.City", "City")
                        .WithMany("Restaurants")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("FK__Restauran__CityI__5070F446");

                    b.HasOne("FoodOrderingApplicationFigma.Models.State", "State")
                        .WithMany("Restaurants")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("FK__Restauran__State__5165187F");

                    b.HasOne("FoodOrderingApplicationFigma.Models.User", "User")
                        .WithOne("Restaurant")
                        .HasForeignKey("FoodOrderingApplicationFigma.Models.Restaurant", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Restauran__UserI__4F7CD00D");

                    b.Navigation("City");

                    b.Navigation("State");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Review", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Custome__76969D2E");

                    b.HasOne("FoodOrderingApplicationFigma.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Restaur__778AC167");

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.User", b =>
                {
                    b.HasOne("FoodOrderingApplicationFigma.Models.Role", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .IsRequired()
                        .HasConstraintName("FK__Users__Roles__RoleID");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.City", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Customer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.MenuItem", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Restaurant", b =>
                {
                    b.Navigation("MenuCategories");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.State", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cities");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("FoodOrderingApplicationFigma.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Admin");

                    b.Navigation("Carts");

                    b.Navigation("Customer");

                    b.Navigation("Orders");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
